### PR TITLE
Updated Client, Contacts and Messages to use respond.io API V2

### PR DESCRIPTION
**Pull request by touson**

### CODE REVIEW

**Review by dooboy — APPROVED** [review]

**Comment by touson** [comment]
@dooboy this is the first time I have ever submitted a pull request to a third party project.  Do I need to do anything else to get this approved commit merged into the main branch in your repo or is this something you do?

**Comment by dooboy** [comment]
@touson if you can merge, then you can merge. but i think only @repat can merge this pull request.

**Comment by touson** [comment]
@repat can you review and merge this pull request?

**Comment by repat** [comment]
Sorry, I was on vacation. I'll have a look and merge!

Thanks :)

**Comment by repat** [comment]
@touson Could you please update the `README.md` accordingly. Since the methods changed, the documentation isn't up to date anymore and people could get confused as to how to use this library without looking at the source code. I will then create a new version (1.0). Thank you!

**Pull request merged**
